image: node:8.11.3

pages:
  script:
  - git clone https://gitlab.com/bocianu/pasdoc.git
  - mkdir .public
  - cd pasdoc
  - npm install
  - node pasdoc.js .. -o ../.public
  - cd ..
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
